[map.rs]
full = "rust"
url = "https://doc.rust-lang.org"
search = "https://doc.rust-lang.org/std/index.html?search={}"
play = "https://play.rust-lang.org/"
rep = "https://github.com/rust-lang/rust"

[map.dcf]
full = "doc config"
url = "https://github.com/wangxdmm/doc_config"

[map.rsb]
full = "rustbook"
url = "https://doc.rust-lang.org/book/"
search = "https://doc.rust-lang.org/book/?search={}"
rep = "https://github.com/rust-lang/book"

[map.cr]
full = "crates"
url = "https://crates.io/"
search = "https://crates.io/search?q={}"

[map.npm]
url = "https://www.npmjs.com/"
search = "https://www.npmjs.com/search?q={}"

[map.pn]
full = "pnpm"
url = "https://pnpm.io/motivation"
rep = "https://github.com/pnpm/pnpm"

[map.ts]
full = "typescript"
url = "https://www.typescriptlang.org/docs/"
play = "https://www.typescriptlang.org/play"

[map.vue]
url = "https://vuejs.org/api/"
rep = "https://github.com/vuejs/"
play = "https://play.vuejs.org/"

[map.uno]
full = "unocss"
url = "https://unocss.dev/interactive/"
rep = "https://github.com/unocss/unocss"
play = "https://unocss.dev/play/"

[map.icf]
full = "iconify"
url = "https://icon-sets.iconify.design/"
rep = "https://github.com/iconify"
search = "https://icon-sets.iconify.design/?query={}"

[map.mdn]
url = "https://developer.mozilla.org/en-US/"
search = "https://developer.mozilla.org/en-US/search?q={}"

[map.emo]
full = "emoji"
url = "https://apps.timwhitlock.info/emoji/tables/unicode"

[map.tom]
full = "tomal"
url = "https://toml.io/en/v1.0.0"

[map.clashv]
full = "clash-verge-rev"
url = "https://clash-verge-rev.github.io/guide.html"