[map]

[map.rs]
full = "rust"
url = "https://doc.rust-lang.org"
search = "https://doc.rust-lang.org/std/index.html?search={}"
play = "https://play.rust-lang.org/"
rep = "https://github.com/rust-lang/rust"

[map.rsb]
full = "rustbook"
url = "https://doc.rust-lang.org/book/"
search = "https://doc.rust-lang.org/book/?search={}"
rep = "https://github.com/rust-lang/book"

[map.cr]
full = "crates"
url = "https://crates.io/"
search = "https://crates.io/crates/{}"
